// @flow

export const SET_TABLE: "SET_TABLE" = "SET_TABLE";
export const ADD_ROW: "ADD_ROW" = "ADD_ROW";
export const DELETE_ROW: "DELETE_ROW" = "DELETE_ROW";
export const SET_CLOSE_VALUES: "SET_CLOSE_VALUES" = "SET_CLOSE_VALUES";
export const ADD_AMOUNT: "ADD_AMOUNT" = "ADD_AMOUNT";
export const SET_ROW_PERCENTS: "SET_ROW_PERCENTS" = "SET_ROW_PERCENTS";
